name: Clang format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flake8
        run: pip install flake8==4.0.1

      - name: Run Flake8
        run: flake8 --max-line-length=80 .
